apiVersion: 1

datasources:
  # https://grafana.com/docs/grafana/latest/datasources/postgres/#provisioning-example
  - name: QuestDB
    type: postgres
    access: proxy
    url: questdb:8812
    database: qdb
    user: admin
    uid: 2Bi8EToVz # the uid is used in the dashboard JSON file
    jsonData:
      postgresVersion: 9.3
      sslmode: disable
      timescaledb: false
    # https://grafana.com/docs/grafana/latest/administration/provisioning/#using-environment-variables
    secureJsonData:
      password: ${GRAFANA_QUESTDB_PASSWORD}